### ISSUE TITLE
S3 backend prioritizes node role over service account

### ISSUE THREAD

**Issue by innovate-invent** [distribution/distribution#3275]
I am attempting to set up a pull through proxy for my AWS EKS cluster.

AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE are set for the container and AWS_ROLE_ARN is the _service account role_ with S3 permissions via IRSA.

Bashing in and running `wget -qO- http://169.254.169.254/latest/meta-data/iam/security-credentials/` returns the _node role_ (expectedly).

registry fails to start with "Access denied" and S3 access logs report the _node role_.

The registry should prioritize the _service account role_ over the _node role_. 

This is likely an issue with the underlying awsgo library but I am opening an issue here to start.

Related: #2172

**Comment by ingshtrom** [comment]
#3245 should fix this

**Comment by michaeljguarino** [comment]
Was this fixed by #3245? I'm running a registry in EKS now and not seeing it take on the IRSA role.

**Comment by leandrocostam** [comment]
> Was this fixed by #3245? I'm running a registry in EKS now and not seeing it take on the IRSA role.

I'm also facing the same issue.

**Comment by switchboardOp** [comment]
> Was this fixed by #3245? I'm running a registry in EKS now and not seeing it take on the IRSA role.

As far as I can tell, no.

**Comment by switchboardOp** [comment]
Yesterday i built this docker image from `master` and was able to use IRSA. 
As far as I can tell though the changes from #3245 are not present in any of the most recent tags on Docker Hub. 

Not being familiar with the build/release cadence of this project I wonder what it takes to get a new dot release built and pushed.

**Comment by switchboardOp** [comment]
For anyone reading this after the 2.8.0 release, it still doesn't support IRSA based on my testing.

**Comment by svadnala** [comment]
can confirm that with `2.8.1` still persists  with same error

`time="2022-04-26T20:08:29.773572268Z" level=error msg="response completed with error" err.code=unknown err.detail="s3aws: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors" err.message="unknown error`

@switchboardOp  did you infer that building the dockerfile from master/main branch and using it instead of published image worked for you?

**Comment by milosgajdos** [comment]
Build of `main` or use `[edge](https://hub.docker.com/layers/distribution/distribution/distribution/edge/images/sha256-1689ce0b5e01ed75069f2f4fe183cdcf62549e21290a1861b68a2c793f73cf6c?context=repo)` tag from distribution Hub repo

**Comment by smartpierre** [comment]
I can confirm, 2.8.1 is not working with IRSA 😔

**Comment by switchboardOp** [comment]
> @switchboardOp did you infer that building the dockerfile from master/main branch and using it instead of published image worked for you?

🎯 Yes. That's what is working for me. Built from the main branch about 2 months ago.

**Comment by jonnymccullagh** [comment]
@switchboardOp for the image you built could you push/tag it somewhere for others to try?
I am stuck with this same problem

**Comment by fredrikhgrelland** [comment]
> @switchboardOp for the image you built could you push/tag it somewhere for others to try? I am stuck with this same problem

This is an older build, but comes directly from the source distribution/distribution@sha256:79dfd00f73f4c258c38457dd0364fd31f80e996713286cb9ab601206de6085fb

This kustomize will work with irsa from the default helm chart:

**Comment by benjimin** [comment]
I just locally built the docker image for the latest commit (3b8fbf975279fb3a1fd1f294980635f94eba4dd4), pushed the image to [cesiumfrog/registry](https://hub.docker.com/repository/docker/cesiumfrog/registry) and tested it (in a kubernetes deployment using a service account with an IAM policy granting S3 access) and it _worked_ (with the registry running as a pull-through mirror, I can set up a port-forward and check e.g. `docker pull 127.0.0.1:5000/ubuntu/postgres` succeeds and that the expected layer blobs have appeared inside my s3 bucket).

Hopefully this means the problem has been **fixed**, and all we need is to wait for the maintainers to tag a 2.8.2 release.

**Comment by milosgajdos** [comment]
Note that you don't need to build the registry instance yourself if you want the latest commit. We push the latest builds to Docker Hub tagged with `edge` tag: https://hub.docker.com/repository/docker/distribution/distribution/tags?page=1&ordering=last_updated

**Comment by gp42** [comment]
Leaving this note for other people trying to use this workaround.
Took me some time to realise that `@edge` build does not work (access to registry fails with messages in logs `blob unknown to registry`), but the build mentioned in https://github.com/distribution/distribution/issues/3275#issuecomment-1232546005 does work, so there must be something wrong with the latest master.

**Comment by mikecook** [comment]
The changes in https://github.com/distribution/distribution/pull/3599 got merged in https://github.com/distribution/distribution/pull/3606

**Comment by mikecook** [comment]
> @mikecook That was on the main branch which currently hasn't been released. That is why this issue is still open, since with the current releases this problem still exists.

Ah! I see. Thanks, I missed that.

**Comment by GowriRegistry** [comment]
To add weightage,
TanzuNetwork Production has high dependency/blocker on Assume Role feature, based on organisation legal demands. There is zero tolerance observed currently and its important for the team to maintain the production platform to be compliant
https://github.com/distribution/distribution/issues/3923 has been closed as duplicate to track here.

**Comment by jackivanov** [comment]
What's ETA to make it a stable release?

**Comment by DavidSpek** [comment]
There (sadly) is not ETA for the v3 release. There is a milestone for it. However, some of the issues/PRs in that milestone are very old and could possibly be pushed or dropped. The main word that’s blocking the v3 release is regarding the OCI compliance for the upcoming OCI release. See the following PRs for reference:
- https://github.com/distribution/distribution/pull/3834
- https://github.com/distribution/distribution/pull/3869
- https://github.com/distribution/distribution/pull/3902

**Comment by thiagoabdo** [comment]
Could it be ported to v2?

**Comment by DavidSpek** [comment]
That's what my PR https://github.com/distribution/distribution/pull/3921 does. But as it stands it will not get merged as all effort is being put into release v3 and the current release branch is only accepting security fixes.

**Comment by GBwandersoncamargo** [comment]
I am receiving this error too, but I discovered it happens because I deployed it in Kubernetes with Istio sidecars.

Istio redirect all network traffic to its sidecar.

Sometimes, on startup, Registry starts before Istio and in that time, there isn't network, so Registry triggers a panic error informing the credentials are unavailable.

I think it happens because Registry tries to retrieve credentials from IAM via HTTP. As it receives a network failure, no credentials are available, triggering the panic error.

**Comment by milosgajdos** [comment]
With the new release out https://github.com/distribution/distribution/releases/tag/v3.0.0-alpha.1 I'm inclined to closing this issue. Do you mind testing the new release and close this @innovate-invent thanks

**Comment by innovate-invent** [comment]
This is great to see but I have moved on from the position that required this and won't be able to test it.

**Comment by milosgajdos** [comment]
Closing. If the issues persists, we will reopen.
